version: "3.7"

services:
  mumbuca_database:
    image: postgres
    container_name: mumbuca_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=mumbu1234
      - POSTGRES_DB=mumbuca
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: mumbuca-api
    ports:
      - 3333:3333
    volumes:
     - .:/usr/app
     - /usr/src/app/node_modules

volumes:
  pgdata:
    driver: local